# Generated by Django 4.1.5 on 2023-01-23 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0002_alter_post_options_post_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='img/blog/cat-widget1.jpg', upload_to='img/blog'),
        ),
    ]
