# Generated by Django 4.1.5 on 2023-01-23 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Mainweb', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['-created_date']},
        ),
    ]
